version: "3"
services:
    server: 
      build:
        context: .
        dockerfile: Dockerfile
      depends_on: 
        - db
      ports:
        - "8080:8080"
      volumes: 
        - .:/app
        - /app/node_modules
    db:
      image: mongo
      restart: always
      expose: 
        - "27017"
      volumes:
        - ./mongodata:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  server:
  db: